name: flutter_login_app
description: "A new Flutter project."
publish_to: 'none' # This prevents publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.6
  image_picker: ^1.0.7
  pdf: ^3.10.4
  printing: ^5.12.0
  fl_chart: ^0.64.0   # ✅ Chart package for dashboard graphs
  rename: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/2.jpg
    - assets/images/3.jpg
    - assets/images/1.png
